---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git
    # On Ubuntu 12.04 build may fail with the following error:
    #   python-build: wget (< 1.14) doesn't support Server Name Indication.
    #   Please install curl (>= 7.18.1) and try again
    - curl

- name: Install development packages necessary for building Python
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - libreadline-dev

- name: Install PyEnv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_path }}"
    update: "{{pyenv_update_git_install}}"
  become_user: "{{pyenv_owner}}"

- name: Install PyEnv-virtualenv plugin
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"
    update: "{{pyenv_update_git_install}}"
  become_user: "{{pyenv_owner}}"

- name: Install .pyenvrc
  template:
    src: ".pyenvrc.j2"
    dest: "{{ pyenv_path }}/.pyenvrc"
    owner: "{{ pyenv_owner }}"
    group: "{{ pyenv_owner }}"
    mode: "0644"

- name: Modify .bashrc
  lineinfile: dest="~/.bashrc"
              regexp="\.pyenvrc$"
              line="source {{ pyenv_path }}/.pyenvrc"
              state=present
  become_user: "{{pyenv_owner}}"

- name: Install Python interpreters "{{ pyenv_python_versions }}"
  shell: . {{ pyenv_path }}/.pyenvrc && pyenv install {{ item }}
         creates="{{ pyenv_path }}/versions/{{ item }}/bin/python"
  with_items: "{{pyenv_python_versions}}"
  become_user: "{{pyenv_owner}}"

- name: Create virtual environments
  shell: . {{ pyenv_path }}/.pyenvrc && pyenv virtualenv {{ item.py_version }} {{ item.venv_name }}
         creates="{{ pyenv_path }}/versions/{{ item.venv_name }}/bin/python"
  with_items: "{{pyenv_virtualenvs}}"
  become_user: "{{pyenv_owner}}"
