---
# Use action module which can interchangably use yum or dnf depending on what is available ( Eg. dnf on Fedora vs yum on Centos )
# Note: special variable ansible_pkg_mgr requires fact_gathering to be enabled
# More: https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/installing_packages/
- name: Install development packages necessary for building Python
  action: >
    {{ ansible_pkg_mgr }} name="{{ pyenv_redhat_packages }}" state=present
  become: true
